#pragma once
#include <ncurses.h>
#include <cstddef>
#include <vector>
#include <string>

#define COLUMNS_SPLIT_RATIO 0.7

class Interactive_shell
{
public:
    bool exit = false;
    
    Interactive_shell();
    ~Interactive_shell();

    void update();
private:
    // ncurses windows
    WINDOW *_main_window;
    WINDOW *_left_window;
    WINDOW *_right_window;

    // previous terminal size to handle resizing
    std::size_t _prev_term_height, _prev_term_width, _prev_left_width, _prev_right_width;

    // autoscroll after every issued command
    bool _autoscroll = false;
    // this variable stores how much the scroll was modified counting from
    // the original scroll position generated by autoscroll or normal scroll
    long long _scroll_pos = 0;

    // vector stores every line typed in shell window
    std::vector<std::string> _shell_lines;
    // this variable stores the FIRST displayed line (the oldest one, displayed at the top of the screen)
    std::size_t _first_shell_line = 0;
    // this variable stores the current position of the cursor in the last (editable) shell line
    std::size_t _cursor_pos;
    // this variable stores the current rewind index
    // set to the last index in the _shell_lines after each ENTER
    // modified during KEY_UP, KEY_DOWN events
    // points to the string that should be copied in place of current line
    std::size_t _rewind_index = 0;

    void _resize_UI(std::size_t new_term_height, std::size_t new_term_width);
    void _redraw_all();
    void _redraw_Shell();
    void _redraw_Help();
    void _redraw_Hotkeys_help();
};
